# Lecture 7-1
- Learining rate, data preprocessing, overfitting

#### gradient descent
- Learning rate 임의의 값으로 잡아줌.
- 큰 값을 잡아주면 over shooting이 될 수가 있다.
- Lr을 정해주는데 답은 없으나, 0.01 정도 정해주며 발산 하면 값을 작게 이런식으로 조절해준다....음

#### Preprocessing
- zero-centered data
- normalized data 

#### over fitting
- test data에는 잘 맞지 않음
-- data의 갯수를 늘린다 / feature가 중복 된 것을 줄여준다.
- regularizaition

# lec 7-2

#### Training / validation / test sets

# ML lab 07-1
### learning rate은 너무 크게 주면 cost 가 nan값이 떠버림
### learning rate 값을 너무 작게 주면 정확도가 떨어짐

In [3]:
# Lab 7 Learning rate and Evaluation
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(
    learning_rate=1e-1).minimize(cost)


# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 5.73203 [[ 0.72881663  0.71536207 -1.18015325]
 [-0.57753736 -0.12988332  1.60729778]
 [ 0.48373488 -0.51433605 -2.02127004]]
1 3.318 [[ 0.66219079  0.74796319 -1.14612854]
 [-0.81948912  0.03000021  1.68936598]
 [ 0.23214608 -0.33772916 -1.94628811]]
2 2.0218 [[ 0.64342022  0.74127686 -1.12067163]
 [-0.81161296 -0.00900121  1.72049117]
 [ 0.2086665  -0.35079569 -1.909742  ]]
3 1.97109 [[ 0.62353212  0.74008238 -1.09958899]
 [-0.80967712 -0.01636279  1.72591698]
 [ 0.17870612 -0.33665746 -1.89391983]]
4 1.94468 [[ 0.60733104  0.73664987 -1.07995546]
 [-0.7900784  -0.03363196  1.72358739]
 [ 0.16691469 -0.3340635  -1.88472235]]
5 1.92357 [[ 0.59031737  0.73510242 -1.06139433]
 [-0.77496767 -0.0404885   1.71533322]
 [ 0.150766   -0.32209399 -1.88054323]]
6 1.90359 [[ 0.57437915  0.73262858 -1.04298222]
 [-0.75527775 -0.05152002  1.70667481]
 [ 0.13977794 -0.31497926 -1.87666988]]
7 1.88408 [[ 0.55812663  0.7307179  -1.02481902]
 [-0.73775685 -0.05928205  1.69691598]
 [ 0.1269844  -0.30

127 0.835461 [[-0.72505975  0.39029613  0.59878933]
 [ 0.21665919  0.04094772  0.64227003]
 [-0.35652775 -0.34020743 -1.35513544]]
128 0.831857 [[-0.73208088  0.38807628  0.60803032]
 [ 0.21998002  0.04400803  0.63588887]
 [-0.35741979 -0.34250563 -1.35194516]]
129 0.828304 [[-0.73906505  0.38587779  0.61721295]
 [ 0.22326447  0.04704344  0.62956899]
 [-0.3582831  -0.34477952 -1.34880793]]
130 0.824801 [[-0.74601257  0.38370067  0.62633759]
 [ 0.22651269  0.05005348  0.62331074]
 [-0.35911781 -0.34702873 -1.34572399]]
131 0.821347 [[-0.75292379  0.38154495  0.63540453]
 [ 0.22972491  0.05303767  0.61711431]
 [-0.3599239  -0.34925285 -1.34269381]]
132 0.817943 [[-0.75979906  0.37941065  0.64441413]
 [ 0.23290129  0.0559956   0.61097997]
 [-0.36070144 -0.35145152 -1.33971763]]
133 0.814588 [[-0.76663876  0.37729776  0.65336668]
 [ 0.23604198  0.05892688  0.60490799]
 [-0.36145058 -0.35362434 -1.33679569]]
134 0.81128 [[-0.7734431   0.37520626  0.66226256]
 [ 0.23914725  0.06183105  0.598

 ### non - normalized inputs의 경우
 - 그래프에서 튕겨 나가버릴 수도 있다!!

In [4]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility


xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  9.30746e+11 
Prediction:
 [[  680315.625 ]
 [ 1372032.375 ]
 [ 1078821.375 ]
 [  755537.4375]
 [  890862.5625]
 [  898384.625 ]
 [  823220.375 ]
 [ 1048780.    ]]
1 Cost:  1.02259e+27 
Prediction:
 [[ -2.25570655e+13]
 [ -4.54096868e+13]
 [ -3.57221616e+13]
 [ -2.50410456e+13]
 [ -2.95122114e+13]
 [ -2.97606085e+13]
 [ -2.72766285e+13]
 [ -3.47285708e+13]]
2 Cost:  inf 
Prediction:
 [[  7.47684373e+20]
 [  1.50516534e+21]
 [  1.18405925e+21]
 [  8.30019252e+20]
 [  9.78222020e+20]
 [  9.86455515e+20]
 [  9.04120636e+20]
 [  1.15112527e+21]]
3 Cost:  inf 
Prediction:
 [[ -2.47830076e+28]
 [ -4.98907394e+28]
 [ -3.92472431e+28]
 [ -2.75121105e+28]
 [ -3.24244908e+28]
 [ -3.26974011e+28]
 [ -2.99683006e+28]
 [ -3.81556043e+28]]
4 Cost:  inf 
Prediction:
 [[  8.21466349e+35]
 [  1.65369600e+36]
 [  1.30090298e+36]
 [  9.11926054e+35]
 [  1.07475363e+36]
 [  1.08379959e+36]
 [  9.93339805e+35]
 [  1.26471908e+36]]
5 Cost:  inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 

 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
86 Cost:  nan 
Prediction:
 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
87 Cost:  nan 
Prediction:
 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
88 Cost:  nan 
Prediction:
 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
89 Cost:  nan 
Prediction:
 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
90 Cost:  nan 
Prediction:
 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
91 Cost:  nan 
Prediction:
 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
92 Cost:  nan 
Prediction:
 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
93 Cost:  nan 
Prediction:
 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
94 Cost:  nan 
Prediction:
 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
95 Cost:  nan 
Prediction:
 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
96 C

#### 따라서 Minmax scaler를 해준다.


In [5]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility


def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)


xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

# very important. It does not work without it.
xy = MinMaxScaler(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)



[[ 0.99999999  0.99999999  0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881782  0.83755791]
 [ 0.54412549  0.50274824  0.57608696  0.606468    0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.42582389  0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.42582389  0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]
0 Cost:  0.167284 
Prediction:
 [[ 0.81795692]
 [ 0.00129694]
 [ 0.36971432]
 [ 0.76176935]
 [ 0.60525566]
 [ 0.56455904]
 [ 0.69530797]
 [ 0.34601137]]
1 Cost:  0.167283 
Prediction:
 [[ 0.81796134]
 [ 0.00130147]
 [ 0.36971745]
 [ 0.7617709 ]
 [ 0.60525823]
 [ 0.56456137]
 [ 0.69530851]
 [ 0.346012  ]]
2 Cost:  0.167282 
Prediction:
 [[ 0.81796569]
 [ 0.001306  ]
 [ 0.36972058]
 [ 0.76177251]
 [ 0.60526073]
 [ 0.56456375]
 [ 0.69530898]
 [ 0.34601262]]
3 Cost:  0.167281 
Prediction:
 [[ 0

94 Cost:  0.167193 
Prediction:
 [[ 0.81836927]
 [ 0.00172126]
 [ 0.37000823]
 [ 0.76191771]
 [ 0.605492  ]
 [ 0.56478041]
 [ 0.69535494]
 [ 0.34607032]]
95 Cost:  0.167192 
Prediction:
 [[ 0.81837368]
 [ 0.00172579]
 [ 0.37001133]
 [ 0.76191926]
 [ 0.6054945 ]
 [ 0.56478274]
 [ 0.69535542]
 [ 0.34607095]]
96 Cost:  0.167191 
Prediction:
 [[ 0.81837803]
 [ 0.00173026]
 [ 0.37001449]
 [ 0.76192081]
 [ 0.605497  ]
 [ 0.56478512]
 [ 0.69535589]
 [ 0.3460716 ]]
97 Cost:  0.16719 
Prediction:
 [[ 0.81838244]
 [ 0.00173479]
 [ 0.37001762]
 [ 0.76192242]
 [ 0.60549951]
 [ 0.56478745]
 [ 0.69535643]
 [ 0.3460722 ]]
98 Cost:  0.167189 
Prediction:
 [[ 0.81838679]
 [ 0.00173926]
 [ 0.37002072]
 [ 0.76192403]
 [ 0.60550201]
 [ 0.56478977]
 [ 0.69535691]
 [ 0.34607285]]
99 Cost:  0.167188 
Prediction:
 [[ 0.8183912 ]
 [ 0.00174379]
 [ 0.37002385]
 [ 0.76192558]
 [ 0.60550451]
 [ 0.56479216]
 [ 0.69535738]
 [ 0.34607348]]
100 Cost:  0.167187 
Prediction:
 [[ 0.81839561]
 [ 0.00174832]
 [ 0.37002701

# ML lab 7-2 

#### 28*28 = 784개

In [7]:
# Lab 7 Learning rate and Evaluation
import tensorflow as tf
import random
# import matplotlib.pyplot as plt
tf.set_random_seed(777)  # for reproducibility

from tensorflow.examples.tutorials.mnist import input_data
# Check out https://www.tensorflow.org/get_started/mnist/beginners for
# more information about the mnist dataset
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

nb_classes = 10

# MNIST data image of shape 28 * 28 = 784
X = tf.placeholder(tf.float32, [None, 784])
# 0 - 9 digits recognition = 10 classes
Y = tf.placeholder(tf.float32, [None, nb_classes])

W = tf.Variable(tf.random_normal([784, nb_classes]))
b = tf.Variable(tf.random_normal([nb_classes]))

# Hypothesis (using softmax)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Test model
is_correct = tf.equal(tf.arg_max(hypothesis, 1), tf.arg_max(Y, 1))
# Calculate accuracy
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# parameters
training_epochs = 15
batch_size = 100

with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    # Training cycle
    for epoch in range(training_epochs):
        avg_cost = 0
        total_batch = int(mnist.train.num_examples / batch_size)

        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            c, _ = sess.run([cost, optimizer], feed_dict={
                            X: batch_xs, Y: batch_ys})
            avg_cost += c / total_batch

        print('Epoch:', '%04d' % (epoch + 1),
              'cost =', '{:.9f}'.format(avg_cost))

    print("Learning finished")

    # Test the model using test sets
    print("Accuracy: ", accuracy.eval(session=sess, feed_dict={
          X: mnist.test.images, Y: mnist.test.labels}))

    # Get one and predict
    r = random.randint(0, mnist.test.num_examples - 1)
    print("Label: ", sess.run(tf.argmax(mnist.test.labels[r:r + 1], 1)))
    print("Prediction: ", sess.run(
        tf.argmax(hypothesis, 1), feed_dict={X: mnist.test.images[r:r + 1]}))

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Epoch: 0001 cost = 2.815904238
Epoch: 0002 cost = 1.139429999
Epoch: 0003 cost = 0.906001778
Epoch: 0004 cost = 0.791949787
Epoch: 0005 cost = 0.718807043
Epoch: 0006 cost = 0.667596697
Epoch: 0007 cost = 0.628468852
Epoch: 0008 cost = 0.596666453
Epoch: 0009 cost = 0.571701703
Epoch: 0010 cost = 0.549652037
Epoch: 0011 cost = 0.531128026
Epoch: 0012 cost = 0.514913795
Epoch: 0013 cost = 0.500757298
Epoch: 0014 cost = 0.488369268
Epoch: 0015 cost = 0.476707373
Learning finished
Accuracy:  0.8898
Label:  [5]
Prediction:  [5]


# lec 8-1 딥러닝의 기본 개념 : 시작과 XOR 문제

#### XOR problem : linearly seperable
- 여러개를 겹치는 건 가능하나, 그러면 w,b를 조절하기가 힘들어짐

#### backpropagation : 
- 에러를 앞에서 뒤로 전이시키자

#### CNN : Convolutional Neural networks
: 어떤 사진이냐에 따라서 자극되는 시신경이 달라짐

: 부분 부분으로 잘라서 넘긴다.

#### A BIG problem
- back propagation이 몇개정도 layer에서는 작동이 되지만 10여개 이상 정도 되버리면, error가 layer를 거꾸로 넘어갈수록 의미가 희미해짐

# lec 8-2

#### CIFAR 단체!

## Breakthrough
#### 처음에 초기 값을 잘주면 layer가 여러개여도 가능하다고 논문을 씀
#### 이때 이름을 Deep learning으로 이름을 바꿈

### 그리고 나서 등장한 것이 image net

#### 최근 활용 
#### Deep api learning도 있음! api추천 시스템 / alphago

# ML lab 08 : Tensor Manipulation

In [9]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

#### 1차원

In [10]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


#### 2차원의 경우

In [11]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


In [12]:
t[1:3,1:4]

array([[ 5.,  6.],
       [ 8.,  9.]])

#### shape, rank, Axis
#### rank []의 개수
#### shape 원소의 개수 = rank의 개수
#### shape의 원소의 의미 = 끝에 값이면 제일 안의 원소의 개수
#### axis는 축의 안쪽에서 3,2,1,0 큰 순서로

In [13]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4], dtype=int32)

In [14]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [15]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4], dtype=int32)

In [16]:
# 위에 것을 눈에 띄게 써준 것
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

#### 메트릭스 곱과 그냥 곱

In [17]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).eval()

array([[ 12.]], dtype=float32)

In [18]:
(matrix1*matrix2).eval()
# 브로드 캐스팅 결과

array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)

#### 브로드 캐스팅

In [19]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [20]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.]], dtype=float32)

#### reduce mean

In [21]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [22]:
x = [[1., 2.],
     [3., 4.]]


tf.reduce_mean(x).eval()

2.5

In [23]:
tf.reduce_mean(x, axis=0).eval()
# axis는 축을 기준으로 나눠준다.

array([ 2.,  3.], dtype=float32)

In [24]:
tf.reduce_mean(x, axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [25]:
tf.reduce_mean(x, axis=-1).eval()

array([ 1.5,  3.5], dtype=float32)

####  argmax의 경우

In [26]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [27]:
tf.argmax(x, axis=1).eval()

array([2, 0])

In [28]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

# Reshape, squeeze, expand_dims

In [29]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [32]:
tf.reshape(t, shape=[-1, 3]).eval()
# 안에 것을 3개로 하고 나머지는 알아서 정해라(-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [36]:
tf.squeeze([[0], [1], [2]]).eval()
# [[]]이런게 많을때 합쳐줄라고!

array([0, 1, 2], dtype=int32)

In [39]:
tf.expand_dims([0, 1, 2], 1).eval()
# 차원을 추가시켜준다.

array([[0],
       [1],
       [2]], dtype=int32)


# One hot

In [44]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()
# depth 값은 카테고리 값이 몇개인줄을 말해줌
# 지금은 총 3개니까!
# 차원이 하나 증가했는데, 밑에것 처럼 rehsape해주어야 한다.

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [45]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

# casting

In [46]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [47]:

tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)


# Stack

In [48]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [49]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

# Ones like and Zeros like

In [50]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [51]:

tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

# Zip

In [52]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [54]:
# 음 3가지도 묶을 수 있군...
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


# Lec 9-1 : XOR문제 딥러닝으로 풀기

### Forward Propagation
: 2개 - 1개 연결해서 해결가능

: 2개를 하나로 표현 가능(행렬형식으로~)

# Lec 9-2 : 딥 네트워크 학습 시키기
#### x1, x2, x3등이 있을 때, layer를 타고 가서 최종적인 y에 미치는 정도를 알아보려고 미분을 하게 된다.
#### Backpropagation (chain rule)
- 간단한 개념이지만 중요!

#### layer 없이 하면 정확도는 0.5!!!

In [55]:
# Lab 9 XOR
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.1

x_data = [[0, 0],
          [0, 1],
          [1, 0],
          [1, 1]]
y_data = [[0],
          [1],
          [1],
          [0]]
x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run(W))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 0.902682 [[ 0.01363677]
 [-0.286437  ]]
100 0.69718 [[ 0.30398455]
 [ 0.13769707]]
200 0.694882 [[ 0.19965401]
 [ 0.11077718]]
300 0.693918 [[ 0.12868384]
 [ 0.08119749]]
400 0.693493 [[ 0.08353963]
 [ 0.05817033]]
500 0.693303 [[ 0.05460777]
 [ 0.04105483]]
600 0.693218 [[ 0.03590658]
 [ 0.02866635]]
700 0.693179 [[ 0.02372674]
 [ 0.01985893]]
800 0.693162 [[ 0.0157427 ]
 [ 0.01367645]]
900 0.693154 [[ 0.01048039]
 [ 0.00937658]]
1000 0.69315 [[ 0.00699623]
 [ 0.00640655]]
1100 0.693148 [[ 0.00468071]
 [ 0.00436572]]
1200 0.693148 [[ 0.00313718]
 [ 0.00296888]]
1300 0.693147 [[ 0.00210564]
 [ 0.00201574]]
1400 0.693147 [[ 0.0014149 ]
 [ 0.00136689]]
1500 0.693147 [[ 0.00095165]
 [ 0.00092601]]
1600 0.693147 [[ 0.0006405 ]
 [ 0.00062681]]
1700 0.693147 [[ 0.00043143]
 [ 0.00042411]]
1800 0.693147 [[ 0.00029067]
 [ 0.00028676]]
1900 0.693147 [[ 0.00019591]
 [ 0.00019382]]
2000 0.693147 [[ 0.00013208]
 [ 0.00013097]]
2100 0.693147 [[  8.90615484e-05]
 [  8.84674955e-05]]
2200 0.693147 

#### - layer하나를 추가해주자!

In [58]:
# Lab 9 XOR
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.1

x_data = [[0, 0],
          [0, 1],
          [1, 0],
          [1, 1]]
y_data = [[0],
          [1],
          [1],
          [0]]
x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

# input은 2로 output은 임의로 정하는 것 가능(2라고 해줌) 
W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

# layer 입력이 2여서 2로 넣어줌
W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run([W1, W2]))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 0.684949 [array([[ 0.24885976,  0.57140535],
       [-0.55108428, -1.42648923]], dtype=float32), array([[-0.29413337],
       [ 1.47008014]], dtype=float32)]
100 0.679357 [array([[ 0.24718435,  0.75729084],
       [-0.55974054, -1.48882806]], dtype=float32), array([[-0.28818822],
       [ 1.5337342 ]], dtype=float32)]
200 0.674561 [array([[ 0.250379  ,  0.92799824],
       [-0.56753045, -1.5814687 ]], dtype=float32), array([[-0.31706607],
       [ 1.59814739]], dtype=float32)]
300 0.668777 [array([[ 0.25647539,  1.09878469],
       [-0.57732528, -1.69673228]], dtype=float32), array([[-0.35115638],
       [ 1.68109131]], dtype=float32)]
400 0.661737 [array([[ 0.26619992,  1.27358985],
       [-0.58978111, -1.83244491]], dtype=float32), array([[-0.39049038],
       [ 1.78371704]], dtype=float32)]
500 0.653266 [array([[ 0.28068036,  1.45468605],
       [-0.60560471, -1.98616219]], dtype=float32), array([[-0.43635696],
       [ 1.90615416]], dtype=float32)]
600 0.643305 [array([[ 0.30144

5500 0.0300484 [array([[ 5.5105381 ,  5.83012581],
       [-5.21521473, -5.97169495]], dtype=float32), array([[-8.13376331],
       [ 8.69045258]], dtype=float32)]
5600 0.0291836 [array([[ 5.53521204,  5.84667397],
       [-5.24015856, -5.98857975]], dtype=float32), array([[-8.18929291],
       [ 8.7425499 ]], dtype=float32)]
5700 0.0283654 [array([[ 5.55909157,  5.86273479],
       [-5.26429939, -6.00499201]], dtype=float32), array([[-8.24332809],
       [ 8.79335976]], dtype=float32)]
5800 0.0275902 [array([[ 5.58222198,  5.87833595],
       [-5.28768444, -6.02095509]], dtype=float32), array([[-8.29594517],
       [ 8.84294128]], dtype=float32)]
5900 0.0268548 [array([[ 5.6046443 ,  5.89349985],
       [-5.31035519, -6.03649092]], dtype=float32), array([[-8.3472147 ],
       [ 8.89134979]], dtype=float32)]
6000 0.0261563 [array([[ 5.62639809,  5.90824938],
       [-5.33235073, -6.05161858]], dtype=float32), array([[-8.39720535],
       [ 8.93863869]], dtype=float32)]
6100 0.0254919 [

#### Wide NN for XOR / Deep NN for XOR
- wide 같은 경우에는 layer 첫번째의 ouput변수와 그 다음 layer의 input변수를 넓게 해준것(크기올려줌)
- deep은 layer의 개수를 늘려준 것

In [59]:
# Lab 9 XOR
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.1

x_data = [[0, 0],
          [0, 1],
          [1, 0],
          [1, 1]]
y_data = [[0],
          [1],
          [1],
          [0]]
x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([10, 10]), name='weight2')
b2 = tf.Variable(tf.random_normal([10]), name='bias2')
layer2 = tf.sigmoid(tf.matmul(layer1, W2) + b2)

W3 = tf.Variable(tf.random_normal([10, 10]), name='weight3')
b3 = tf.Variable(tf.random_normal([10]), name='bias3')
layer3 = tf.sigmoid(tf.matmul(layer2, W3) + b3)

W4 = tf.Variable(tf.random_normal([10, 1]), name='weight4')
b4 = tf.Variable(tf.random_normal([1]), name='bias4')
hypothesis = tf.sigmoid(tf.matmul(layer3, W4) + b4)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run([W1, W2]))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 1.24221 [array([[-1.49504495, -1.14558363, -1.651389  , -0.25908557, -0.49682438,
        -2.37779307,  2.14276886, -2.0465517 ,  1.17003095,  0.27270135],
       [-0.58698732,  1.26714897, -0.47386786,  1.10553908,  0.66053289,
         0.87483901,  1.16862762,  0.3776418 ,  0.09920298,  0.7653411 ]], dtype=float32), array([[ 0.50520235,  0.96971321,  1.86427534, -0.07748947,  0.42074516,
         1.96959436, -0.53498459,  1.29063809, -0.72659332,  0.42336985],
       [-0.55378312, -0.74103916,  2.01812553,  0.84186888,  1.42882633,
         1.36189878,  0.68496245,  0.74027365, -0.010645  ,  0.59458238],
       [ 0.4487583 ,  1.25838327,  0.64698881,  0.3608759 ,  1.37961769,
         0.33558261, -0.22418004, -2.37564373, -1.32276917, -0.6962288 ],
       [ 0.4291167 ,  0.5280627 ,  1.0287298 ,  0.05082946,  0.17430621,
        -0.30797526, -0.04656805,  0.49567571,  0.54136634, -0.76110345],
       [-0.21362859, -1.66202664,  1.50273788, -0.24913508,  1.37983596,
         0.607406

800 0.412333 [array([[-1.57758176, -1.07290971, -1.79574966, -0.19175768, -0.36254427,
        -2.9698081 ,  1.67096865, -2.55592752,  1.21832895,  0.95043474],
       [-0.87156522,  1.67209935, -0.7165339 ,  1.04881299,  0.80130261,
         2.80047274,  1.04721189,  0.67545396,  0.17922689,  1.17260885]], dtype=float32), array([[ 0.48731977,  0.96037072,  1.80723631,  0.05139019,  0.4215726 ,
         2.02266145, -0.69216901,  1.22989905, -0.68339241,  0.42227069],
       [-0.51447242, -0.75863248,  1.99638414,  0.64636528,  1.42811   ,
         1.16489041,  1.4516449 ,  0.78385621, -0.25117639,  0.60521477],
       [ 0.42248607,  1.24448013,  0.51960641,  0.54320341,  1.37968898,
         0.33104452, -0.30918488, -2.50272036, -1.28512514, -0.69210839],
       [ 0.42498702,  0.49551851,  0.88307297,  0.05523342,  0.15167227,
        -0.17319195,  0.22630818,  0.4793888 ,  0.42275339, -0.73385525],
       [-0.22785489, -1.68110669,  1.31685925, -0.26087362,  1.35000205,
         0.677

1600 0.0293093 [array([[-1.64156961, -1.71213019, -1.93138158, -0.14418237, -0.36014423,
        -3.78843451,  1.84022999, -3.24517393,  1.15982687,  1.54695451],
       [-1.11842918,  1.99384201, -1.26651275,  1.04923606,  0.88210976,
         3.97257304,  1.07692432,  1.50728512,  0.14961012,  2.00636148]], dtype=float32), array([[ 0.47949019,  0.95204818,  1.7434932 ,  0.12598602,  0.42303506,
         2.1428299 , -0.84207511,  1.15581512, -0.65726244,  0.41272554],
       [-0.50811487, -0.77664596,  2.01529717,  0.07898468,  1.42603886,
         0.78680873,  2.24394274,  0.89741862, -0.4402239 ,  0.68819737],
       [ 0.40567639,  1.22664464,  0.37477246,  0.63155955,  1.38135564,
         0.54622298, -0.52697068, -2.67045116, -1.24745822, -0.69901639],
       [ 0.40264708,  0.44478956,  0.73424685, -0.10416551,  0.12686288,
        -0.15517148,  0.35728884,  0.47765732,  0.35442251, -0.73592943],
       [-0.2552622 , -1.73316824,  1.13574922, -0.40639776,  1.31952345,
         0.7

2300 0.0117122 [array([[-1.65793502, -1.87006962, -1.96724761, -0.13300301, -0.3693859 ,
        -3.93849063,  1.8936491 , -3.37897396,  1.13351905,  1.68177497],
       [-1.15131211,  2.04491425, -1.3573463 ,  1.04255331,  0.87528503,
         4.17777729,  1.12911975,  1.67029881,  0.14869505,  2.1439147 ]], dtype=float32), array([[ 0.47812083,  0.95137429,  1.73482096,  0.13663071,  0.42305505,
         2.16512918, -0.85933578,  1.14477003, -0.65394992,  0.41159171],
       [-0.50693136, -0.77929783,  2.03305459, -0.05203275,  1.42521644,
         0.71238738,  2.36035872,  0.9169274 , -0.46579421,  0.71098489],
       [ 0.40250075,  1.22523391,  0.35563985,  0.64941037,  1.38111329,
         0.59496516, -0.55993509, -2.69671273, -1.24069834, -0.69998109],
       [ 0.39740598,  0.43724895,  0.71278226, -0.12131969,  0.11966046,
        -0.15951557,  0.37010476,  0.47991991,  0.35252658, -0.73473513],
       [-0.26115641, -1.74044216,  1.11232412, -0.42351118,  1.31100273,
         0.7

3000 0.00702973 [array([[-1.66643214, -1.94967449, -1.98618782, -0.12734066, -0.37548819,
        -4.01117373,  1.92058945, -3.44560385,  1.11973381,  1.75039446],
       [-1.16654682,  2.07366157, -1.40094173,  1.038638  ,  0.87055939,
         4.27805567,  1.15929806,  1.75232065,  0.14847621,  2.21081138]], dtype=float32), array([[ 0.47735482,  0.95109648,  1.73084474,  0.14185297,  0.42303419,
         2.17608809, -0.86730188,  1.13945532, -0.65229553,  0.41109765],
       [-0.5058701 , -0.78051376,  2.0442183 , -0.11941959,  1.42469954,
         0.67443478,  2.41637588,  0.9265216 , -0.47833189,  0.7241863 ],
       [ 0.40072545,  1.22467089,  0.34684792,  0.6590817 ,  1.3809464 ,
         0.6195178 , -0.57599795, -2.70943618, -1.23714781, -0.70042247],
       [ 0.39469165,  0.43371725,  0.70309091, -0.12862816,  0.11568037,
        -0.16233484,  0.37550685,  0.48099232,  0.35279337, -0.73298818],
       [-0.26418397, -1.74378383,  1.10204709, -0.43112925,  1.30636907,
         0.

3800 0.00475156 [array([[-1.67268586, -2.00739241, -2.00027323, -0.12322371, -0.38060138,
        -4.06280947,  1.94016159, -3.49366617,  1.10960758,  1.80040836],
       [-1.17709994,  2.09589267, -1.43181014,  1.03559339,  0.86669797,
         4.34957457,  1.18266451,  1.81173444,  0.14831927,  2.25857902]], dtype=float32), array([[ 0.47675428,  0.95091552,  1.7281028 ,  0.14560169,  0.42301035,
         2.18394279, -0.87282026,  1.13568223, -0.65107691,  0.4107722 ],
       [-0.50480253, -0.78135437,  2.05329013, -0.16892508,  1.42427146,
         0.64660174,  2.45606995,  0.93342513, -0.48735538,  0.7346974 ],
       [ 0.39933351,  1.22430992,  0.3407605 ,  0.6663866 ,  1.38080978,
         0.63734132, -0.58745277, -2.71850133, -1.234465  , -0.70072466],
       [ 0.39271086,  0.43126702,  0.69651842, -0.13350189,  0.1126282 ,
        -0.16456404,  0.37900659,  0.48172638,  0.35359317, -0.73108691],
       [-0.26638401, -1.74607456,  1.09519958, -0.43637365,  1.30285287,
         0.

4300 0.00393432 [array([[-1.67561996, -2.03424764, -2.00692439, -0.12130498, -0.38319618,
        -4.08654594,  1.94928682, -3.51596165,  1.10487306,  1.82374513],
       [-1.1818769 ,  2.106637  , -1.44598162,  1.03411961,  0.86478901,
         4.38252211,  1.19393909,  1.83935213,  0.14822987,  2.28062701]], dtype=float32), array([[ 0.47646031,  0.95083195,  1.72686386,  0.1473376 ,  0.42299545,
         2.18757439, -0.87531888,  1.13394701, -0.65049994,  0.41062972],
       [-0.50419575, -0.78173631,  2.05779576, -0.19214804,  1.42404544,
         0.63354212,  2.4742918 ,  0.93662733, -0.49154046,  0.73990172],
       [ 0.39865062,  1.22414672,  0.33800122,  0.66986972,  1.38075018,
         0.64564234, -0.59272873, -2.7226789 , -1.23317862, -0.7008599 ],
       [ 0.39179257,  0.43015927,  0.69358349, -0.13566321,  0.11115704,
        -0.16564439,  0.38052145,  0.48205352,  0.3541669 , -0.72998887],
       [-0.26740143, -1.74710369,  1.09217644, -0.43875074,  1.30116916,
         0.

5200 0.00299101 [array([[-1.67979109, -2.07219744, -2.01642752, -0.11858982, -0.38711435,
        -4.11979055,  1.96221244, -3.54739738,  1.09816778,  1.85678792],
       [-1.1884886 ,  2.12225127, -1.46581948,  1.03197742,  0.86197704,
         4.42873192,  1.21028769,  1.87834096,  0.14805938,  2.31161904]], dtype=float32), array([[ 0.47602612,  0.95072466,  1.72515202,  0.14978339,  0.42296863,
         2.19268179, -0.8787775 ,  1.13151538, -0.64966977,  0.41044104],
       [-0.50319916, -0.78226453,  2.06447411, -0.22517183,  1.42372358,
         0.61495215,  2.49978852,  0.9411447 , -0.49744087,  0.74764043],
       [ 0.39764273,  1.22393215,  0.33417451,  0.67488396,  1.38064289,
         0.65738326, -0.60012567, -2.72854114, -1.23130584, -0.70104516],
       [ 0.39050713,  0.42862934,  0.68956059, -0.13861379,  0.10902002,
        -0.16721079,  0.38254532,  0.48249841,  0.35521308, -0.72818017],
       [-0.26882321, -1.74851263,  1.08806944, -0.44205406,  1.29873645,
         0.

6000 0.00245822 [array([[-1.68271148, -2.09861279, -2.02311158, -0.11669681, -0.39002651,
        -4.14272785,  1.97123671, -3.56923008,  1.09349763,  1.87982917],
       [-1.19299877,  2.13341641, -1.47950673,  1.03044641,  0.85994542,
         4.46066141,  1.22194469,  1.90544856,  0.14790441,  2.33309221]], dtype=float32), array([[ 0.47571167,  0.95064807,  1.72398806,  0.15148179,  0.42294478,
         2.19621944, -0.88113678,  1.12983871, -0.64908075,  0.41031513],
       [-0.50239581, -0.78262335,  2.06934094, -0.24830234,  1.42347455,
         0.60190988,  2.51736426,  0.94428581, -0.50153691,  0.75331855],
       [ 0.39690986,  1.22378898,  0.33155751,  0.67843825,  1.38054752,
         0.6655643 , -0.60523403, -2.73259091, -1.22996616, -0.70117569],
       [ 0.38962704,  0.42758933,  0.68684018, -0.1406011 ,  0.10749105,
        -0.16832577,  0.3838771 ,  0.48279598,  0.35613841, -0.72672415],
       [-0.2697953 , -1.74946439,  1.08531964, -0.44432089,  1.29700208,
         0.

6700 0.00212336 [array([[-1.68485487, -2.1179347 , -2.02803922, -0.11531019, -0.39225769,
        -4.15940285,  1.97785485, -3.58517361,  1.09008312,  1.8967011 ],
       [-1.19624972,  2.14173388, -1.48945928,  1.02930689,  0.85842168,
         4.48389196,  1.23060822,  1.92525721,  0.14776881,  2.34875154]], dtype=float32), array([[ 0.47547337,  0.95060635,  1.7231468 ,  0.15272236,  0.42292392,
         2.19880152, -0.88283807,  1.12861419, -0.64864254,  0.41022962],
       [-0.50174099, -0.7828843 ,  2.07300758, -0.26529604,  1.42330766,
         0.59231192,  2.53013492,  0.94658124, -0.50452471,  0.75763798],
       [ 0.3963562 ,  1.22370553,  0.3296662 ,  0.68107164,  1.38046408,
         0.67155331, -0.60894918, -2.73554373, -1.22895908, -0.70125914],
       [ 0.38899428,  0.42684156,  0.68488908, -0.14202276,  0.1063506 ,
        -0.16915245,  0.3848125 ,  0.48300755,  0.35692438, -0.72554845],
       [-0.27049303, -1.75015414,  1.08335865, -0.4459644 ,  1.29571652,
         0.

7500 0.00183502 [array([[-1.6869657 , -2.13686728, -2.03289247, -0.1139495 , -0.39453062,
        -4.17566109,  1.98435628, -3.6007731 ,  1.08673787,  1.91324711],
       [-1.19940042,  2.15000558, -1.49916613,  1.02817404,  0.8568992 ,
         4.5065527 ,  1.23920679,  1.94465029,  0.14760768,  2.36406326]], dtype=float32), array([[ 0.47523302,  0.95055866,  1.7223357 ,  0.15393697,  0.42290008,
         2.20132279, -0.88448429,  1.12742329, -0.64820224,  0.41014904],
       [-0.50103933, -0.78313595,  2.07668662, -0.28200874,  1.42311692,
         0.58285707,  2.54257774,  0.94883054, -0.5074448 ,  0.76201582],
       [ 0.39579815,  1.22361016,  0.32783085,  0.68367964,  1.38036871,
         0.6774264 , -0.61257201, -2.7384181 , -1.2279551 , -0.7013545 ],
       [ 0.38838553,  0.42611939,  0.68300575, -0.14339076,  0.10521468,
        -0.16997035,  0.38569939,  0.48320925,  0.35779324, -0.72429925],
       [-0.27116337, -1.75080597,  1.08148134, -0.4475649 ,  1.29443634,
         0.

8300 0.00161393 [array([[-1.6887902 , -2.1532526 , -2.03711414, -0.11277007, -0.3965697 ,
        -4.18966007,  1.98999989, -3.61425519,  1.08384931,  1.92757738],
       [-1.20209575,  2.15725684, -1.50753307,  1.02717853,  0.85555661,
         4.52608728,  1.24673247,  1.96141911,  0.14744079,  2.37729025]], dtype=float32), array([[ 0.47502038,  0.95051098,  1.72163939,  0.15498747,  0.42287624,
         2.20350504, -0.88589519,  1.12640429, -0.64781779,  0.41007751],
       [-0.50037658, -0.78335464,  2.07994556, -0.29652187,  1.42292619,
         0.57463193,  2.55329251,  0.9507761 , -0.50996369,  0.76592779],
       [ 0.39530182,  1.2235148 ,  0.32625553,  0.68595934,  1.38027334,
         0.6825133 , -0.61569351, -2.74090099, -1.22706521, -0.70144057],
       [ 0.38787085,  0.4255029 ,  0.68139756, -0.14455557,  0.10421676,
        -0.17068377,  0.38644385,  0.48338056,  0.35862911, -0.72313458],
       [-0.27173054, -1.75137055,  1.07988   , -0.44894239,  1.29332554,
         0.

9000 0.00145899 [array([[-1.69021177, -2.16595578, -2.04040384, -0.11185402, -0.39819768,
        -4.20047617,  1.9943856 , -3.62469912,  1.08161068,  1.93869472],
       [-1.20417035,  2.1629467 , -1.51400125,  1.02640009,  0.85450464,
         4.54118156,  1.25261939,  1.9744122 ,  0.14729476,  2.38753223]], dtype=float32), array([[ 0.47485349,  0.95046926,  1.72110844,  0.15580159,  0.42285538,
         2.20519829, -0.88697833,  1.12561262, -0.64752007,  0.41002923],
       [-0.49983418, -0.78352153,  2.08252096, -0.30780661,  1.42275929,
         0.56822592,  2.56156278,  0.95228511, -0.51191026,  0.76904505],
       [ 0.39490956,  1.22343135,  0.32504308,  0.68774194,  1.38019931,
         0.68646044, -0.61810488, -2.74281859, -1.22636616, -0.7014823 ],
       [ 0.3874791 ,  0.42502943,  0.68016446, -0.14544775,  0.1034335 ,
        -0.17124096,  0.38700718,  0.48350817,  0.35933328, -0.72217947],
       [-0.27216139, -1.75178778,  1.07866359, -0.4500069 ,  1.29245067,
         0.

9800 0.00131392 [array([[-1.69167805, -2.1789794 , -2.0437851 , -0.11091349, -0.39991081,
        -4.21152544,  1.99889457, -3.63539171,  1.07932186,  1.9500953 ],
       [-1.20627522,  2.1688261 , -1.52061367,  1.025594  ,  0.85341126,
         4.55661058,  1.25870156,  1.98772049,  0.14712787,  2.39801955]], dtype=float32), array([[ 0.47467959,  0.95042157,  1.72055602,  0.15663613,  0.42283154,
         2.20692849, -0.88807845,  1.1248039 , -0.64720368,  0.40998155],
       [-0.49923956, -0.78369844,  2.08520317, -0.31940264,  1.42262542,
         0.56163281,  2.57001138,  0.95383179, -0.51389992,  0.77231932],
       [ 0.39449707,  1.22333598,  0.32380715,  0.68958211,  1.38019931,
         0.69050962, -0.62056851, -2.74478531, -1.22562885, -0.70152998],
       [ 0.38708693,  0.42455012,  0.67891002, -0.14635123,  0.10262195,
        -0.17181401,  0.38757131,  0.48363817,  0.36011049, -0.72114915],
       [-0.27259225, -1.75222313,  1.07742882, -0.45109418,  1.29154634,
         0.

#### Tensor board
- 음 실행이 안되는군...나중에 다시 체크해보기!

In [60]:
# Lab 9 XOR
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility
learning_rate = 0.01

x_data = [[0, 0],
          [0, 1],
          [1, 0],
          [1, 1]]
y_data = [[0],
          [1],
          [1],
          [0]]
x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2], name='x-input')
Y = tf.placeholder(tf.float32, [None, 1], name='y-input')

with tf.name_scope("layer1") as scope:
    W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
    b1 = tf.Variable(tf.random_normal([2]), name='bias1')
    layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

    w1_hist = tf.summary.histogram("weights1", W1)
    b1_hist = tf.summary.histogram("biases1", b1)
    layer1_hist = tf.summary.histogram("layer1", layer1)


with tf.name_scope("layer2") as scope:
    W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
    b2 = tf.Variable(tf.random_normal([1]), name='bias2')
    hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

    w2_hist = tf.summary.histogram("weights2", W2)
    b2_hist = tf.summary.histogram("biases2", b2)
    hypothesis_hist = tf.summary.histogram("hypothesis", hypothesis)

# cost/loss function
with tf.name_scope("cost") as scope:
    cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                           tf.log(1 - hypothesis))
    cost_summ = tf.summary.scalar("cost", cost)

with tf.name_scope("train") as scope:
    train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))
accuracy_summ = tf.summary.scalar("accuracy", accuracy)

# Launch graph
with tf.Session() as sess:
    # tensorboard --logdir=./logs/xor_logs
    merged_summary = tf.summary.merge_all()
    writer = tf.summary.FileWriter("./logs/xor_logs_r0_01")
    writer.add_graph(sess.graph)  # Show the graph

    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        summary, _ = sess.run([merged_summary, train], feed_dict={X: x_data, Y: y_data})
        writer.add_summary(summary, global_step=step)

        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run([W1, W2]))

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 0.875483 [array([[-0.34591606, -0.67055368],
       [ 1.22395468,  0.03936624]], dtype=float32), array([[ 1.26053214],
       [-0.1126683 ]], dtype=float32)]
100 0.680423 [array([[-0.95773917, -0.93033725],
       [ 0.91384035,  0.8835656 ]], dtype=float32), array([[ 0.89668518],
       [-0.60954541]], dtype=float32)]
200 0.625293 [array([[-1.56143105, -2.4558785 ],
       [ 1.45079803,  2.428684  ]], dtype=float32), array([[ 1.22286797],
       [-0.89978796]], dtype=float32)]
300 0.486822 [array([[-2.64485645, -3.84371972],
       [ 2.45610929,  3.87774229]], dtype=float32), array([[ 2.14269543],
       [-1.58425868]], dtype=float32)]
400 0.32377 [array([[-3.74465227, -4.98213577],
       [ 3.50151396,  4.99636459]], dtype=float32), array([[ 3.28265071],
       [-2.4376924 ]], dtype=float32)]
500 0.216091 [array([[-4.52911329, -5.80116892],
       [ 4.28494978,  5.80397224]], dtype=float32), array([[ 4.22543192],
       [-3.22633123]], dtype=float32)]
600 0.152776 [array([[-5.078083

5000 0.00190157 [array([[ -8.95269012, -10.62414932],
       [  8.75141525,  10.65234184]], dtype=float32), array([[ 13.39183617],
       [-12.45720863]], dtype=float32)]
5100 0.00179667 [array([[ -8.98588276, -10.65926838],
       [  8.78458023,  10.68766689]], dtype=float32), array([[ 13.50219631],
       [-12.5688715 ]], dtype=float32)]
5200 0.00169818 [array([[ -9.01860714, -10.6938715 ],
       [  8.81727791,  10.72247505]], dtype=float32), array([[ 13.6118679 ],
       [-12.67981529]], dtype=float32)]
5300 0.00160573 [array([[ -9.05088615, -10.72798538],
       [  8.84952354,  10.75678921]], dtype=float32), array([[ 13.72088718],
       [-12.79008102]], dtype=float32)]
5400 0.00151875 [array([[ -9.08273792, -10.76163292],
       [  8.88134384,  10.79063225]], dtype=float32), array([[ 13.82929707],
       [-12.89970875]], dtype=float32)]
5500 0.00143694 [array([[ -9.11418343, -10.79482937],
       [  8.91274929,  10.82402039]], dtype=float32), array([[ 13.93712711],
       [-13.00

10000 0.000139873 [array([[-10.26658821, -12.00143337],
       [ 10.06265831,  12.03687572]], dtype=float32), array([[ 18.50201988],
       [-17.61198425]], dtype=float32)]

Hypothesis:  [[  1.26781146e-04]
 [  9.99902487e-01]
 [  9.99789417e-01]
 [  1.24602273e-04]] 
Correct:  [[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 
Accuracy:  1.0
